name: dartapi_core
description: A core library for dartapi
version: 0.0.2
repository: https://github.com/akashgk/dartapi_core
homepage: https://github.com/akashgk/dartapi_core
issue_tracker: https://github.com/akashgk/dartapi_core/issues

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
